backend:
  name: github
  repo: tomohikohorai-source/pjn-site # ← ハイフンまで正確に！
  branch: main
  base_url: https://penan-japanese-news.vercel.app
  auth_endpoint: api/auth

# 画像を使わなくてもこれは必須です
media_folder: "public/images"
public_folder: "/images"

# 下書き保存機能
publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "記事一覧"
    folder: "src/pages/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "公開日", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "ジャンル", name: "category", widget: "select", options: ["重要", "コラム", "グルメ", "おでかけ", "暮らし", "教育", "エンタメ", "お得"] }
      - { label: "本文", name: "body", widget: "markdown" }
